version: "3"
services:
    pwn_easy_1:
        image: waveburst/qemu-system-armel
        ports:
            - "20080:80"
            - "20565:5565"
            - "20022:22"
            - "20023:23"
            - "20069:69"
            - "20322:322"
            - "20443:443"
            - "20554:554"
            - "28000:8000"
            - "29010:9010"
            - "29020:9020"
            - "20996:23946"