version: "3"
services:
    pwn_easy_1:
        image: waveburst/qemu-system-armhf
        ports:
            - "30080:80"
            - "30575:5575"
            - "30022:22"
            - "30023:23"
            - "30069:69"
            - "30322:322"
            - "30443:443"
            - "30554:554"
            - "38000:8000"
            - "39010:9010"
            - "39020:9020"
            - "30996:23946"